### ISSUE TITLE
Код слабенький

### ISSUE THREAD

**Issue by Shalopay585** [areyousatisfiede/KNT-132#1]
Тут был какой-то очень смешной текст

**Comment by areyousatisfiede** [comment]
> В целом код использует инструменты для создания цветного текстика в консольке. Но при этом использует черный цвет как подстилку (задний фон) этой самой консоли. Автор расист!

Уважаемый пользователь Shalopay585, мы приняли ваши негодования и скоро исправим, мы на бета тесте.

**Comment by Shalopay585** [comment]
Вы на колесах, а не на бета тесте!1!!

**Comment by areyousatisfiede** [comment]
> Вы на колесах, а не на бета тесте!1!!

Будьте вежливыми с работникам гос компанией UKRTELEKOM.
